#pragma once

constexpr int CONCUSSIVE_SHOT_MANA_COST = 200;
constexpr float CONCUSSIVE_SHOT_COOLDOWN_TIME = 12.0f;
constexpr float CONCUSSIVE_SHOT_DEBUFF_TIME = 8.0f;
constexpr float CONCUSSIVE_SHOT_SPEED_MULTIPLIER = 0.5f;
constexpr float CONCUSSIVE_SHOT_AGGRO_VALUE = 40.0f;
constexpr float CONCUSSIVE_SHOT_PROJECTILE_OFFSET = 0.0f;
