add_library(systems_gameplay
    PlayerMovementSystem.cpp
    PlayerFacingSystem.cpp
    scale/ScalePlayerLocationSystem.cpp
    scale/ScaleNpcLocationSystem.cpp
    scale/ScaleObjectLocationSystem.cpp
    scale/equipment/ScaleEquipmentLocationSystem.cpp
    depth/PlayerDepthSystem.cpp
    depth/NpcDepthSystem.cpp
    depth/ObjectDepthSystem.cpp
    depth/EquipmentDepthSystem.cpp
    depth/EffectDepthSystem.cpp
    flipx/FlipPlayerSystem.cpp
    flipx/FlipNpcSystem.cpp
    flipx/EquipmentFacingSystem.cpp
    flipx/FlipEquipmentSystem.cpp
    rotation/RotateEquipmentSystem.cpp
    equipment/MoveEquipmentSystem.cpp
    projectile/PlayerShootProjectileSystem.cpp
    projectile/MoveEffectSystem.cpp
    projectile/DestroyEffectByDistanceSystem.cpp
    ai/NPCAiSystem.cpp
    ai/astar/FollowAStarPathTo.cpp
    ai/monster/RunMonsterAi.cpp
    ai/monster/HandleMonsterIdle.cpp
    ai/monster/HandleMonsterPatrol.cpp
    ai/monster/HandleMonsterChasePlayer.cpp
    ai/monster/HandleMonsterAttack.cpp
    ai/monster/HandleMonsterReturnToSpawn.cpp
    ai/pet/RunPetAi.cpp
    ai/pet/HandlePetIdle.cpp
    ai/pet/HandlePetFollowPlayer.cpp
    ai/DistToPlayer.cpp
    ai/DistToNpcSpawn.cpp
    ai/HasReachedRect.cpp
    ai/AreColBoxesNear.cpp
    ai/MoveColCenterToward.cpp
    ai/astar/pool/AStarAlloc.cpp
    ai/astar/pool/AStarFree.cpp
    ai/astar/reconstruct/ReconstructPath.cpp
    ai/astar/node/AStarEncode.cpp
    ai/astar/node/AStarDecode.cpp
    ai/astar/cost/AStarH.cpp
    ai/astar/cost/AStarD.cpp
    ai/astar/neighbors/IsBlocked.cpp
    ai/astar/neighbors/GetNeighbors.cpp
    ai/astar/goal/IsGoalReached.cpp
    ai/astar/RunAStar.cpp
    ai/astar/RequestAStarPath.cpp
    collision/CollisionSystem.cpp
    collision/effects/EffectCollisionSystem.cpp
    collision/effects/EffectCollisionResolutionSystem.cpp
    collision/effects/ResolveProjectileEffectCollision.cpp
    collision/CollisionResolutionSystem.cpp
    camera/CameraSystem.cpp
    animation/AnimationSystem.cpp
)
target_include_directories(systems_gameplay PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/ai
    ${CMAKE_CURRENT_SOURCE_DIR}/collision
    ${CMAKE_CURRENT_SOURCE_DIR}/collision/effects
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/pet
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/astar/pool
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/astar/node
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/astar/cost
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/astar/neighbors
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/astar/goal
    ${CMAKE_CURRENT_SOURCE_DIR}/ai/astar
    ${CMAKE_CURRENT_SOURCE_DIR}/camera
    ${CMAKE_CURRENT_SOURCE_DIR}/animation
    ${CMAKE_CURRENT_SOURCE_DIR}/rotation
    ${CMAKE_CURRENT_SOURCE_DIR}/scale/equipment
)
target_link_libraries(systems_gameplay PUBLIC gg2_common)
